# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9449bdf5340438b0359a250dd70c20bd1f97930fc7a18b75522ed5f303cff0fcd61afa6a9affc687e26d251342beb801cfb66f3c3e3f1260780d38005641fb38

test:
  secret_key_base: 65d573d3a94baca8ce182b56fef4cd753133b27953b0d40385109b67ad8e3c8af6d85956ff4223bbb6c2da85eb92fcabdbac2f4927a41b6649f0ff923d4c358b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
